added a console payment tnx object
Chimoney/offline-pay-with-celo pull request #29
Opened 2021-11-19 11:59 UTC by Mlg29

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I need help writing tests.
- [ ] All new and existing tests passed.

2021-11-21 21:17 UTC, uchibeke commented
@Mlg29 do you mind resolving the conflict?

2021-11-21 21:18 UTC, Mlg29 commented
@uchibeke okay. I will look into it

2021-11-22 15:31 UTC, uchibeke requested changes
Could you review the latest main branch. We might not need this change again or try to merge your web3 stuff with what we have in main, if possible

2021-11-22 15:31 UTC, uchibeke commented on packages/offline-pay-with-crypto-widget/src/components/Modal/index.js
>  export function Modal({ config }) {
Please see new config https://github.com/Chimoney/offline-pay-with-celo/blob/main/packages/offline-pay-with-crypto-widget/src/components/Modal/index.js#L39

2021-11-22 15:31 UTC, uchibeke commented on packages/offline-pay-with-crypto-widget/src/components/Modal/index.js
> +    let anAddress = '0x998f2193ae2d887249c27d2ab2ceb9e60be75f7b'
We do not want to hardcode. New changes fixes this https://github.com/Chimoney/offline-pay-with-celo/blob/main/packages/offline-pay-with-crypto-widget/src/components/Modal/index.js#L39

2021-11-22 19:15 UTC, closed without merging